### ISSUE TITLE
Possible release of tech files / tool scripts?

### ISSUE THREAD

**Issue by choltz95** [circuitnet/CircuitNet#6]
Hi,

Thanks again for releasing this dataset! My group is interested in running the same flow used to generate the data. For example, if we want to take a layout from the circuitnet dataset, make an adjustment to the layout, do PR / DRC flow on the adjusted layout, and generate a new set of features / label.

Is there any way to release these details? We are also open to collaboration and willing to discuss more details. Please let me know!

**Comment by apri0426** [comment]
Thank you for supporting CircuitNet! 

Due to the license restriction, we cannot release the tech file and scripts to the public. However, if you have access to the corresponding PDK and have licensed the commercial tools, it might be ok to share some of the scripts. You can send a detailed request through email for further discussion.
